spring: 
   datasource: 
      driverClassName: com.mysql.jdbc.Driver 
      url: jdbc:mysql://localhost:3306/aa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai 
      username: root 
      password: xdj 
      type: com.mchange.v2.c3p0.ComboPooledDataSource 